#!/usr/bin/env python

import optparse
import string
import sys

def read_fasta(file):
   f = open(file,'r')
   lines = []
   for fi in f:
      lines.append(fi)
   f.close()
   return lines

def main():
   if len(sys.argv) < 2:
      print "Syntax: fasta2mig fastafile > migratefile"
      sys.exit()
      

   lines = read_fasta(sys.argv[1])
   print " 1 1 "
   print len(lines[1])
   print len(lines)/2," population 1"
   for line in lines:
      if (line[0] == '>'):
         label= line[1:]
      else:
         print "%-10.10s %s" % (label.strip(),line),


if __name__ == '__main__':
    main()
